---
- hosts: 54.159.204.206
  become: yes
  tasks:
  - name: install mariadb server
    yum:
      name=mariadb-server
      state=latest
    tags:
    - install
  - name: start maria db
    service:
      name=mariadb
      state=started
    tags:
    - start
  - name: add user
    user:
      name=testuser
    tags:
    - user
